=== hmcts/cpp-context-staging-dvla/stagingdvla-datatypes-common/src/main/resources/json/schema/private/materialDetails.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/core/courts/materialDetails.json",
  "description": "The context for material",
  "type": "object",
  "properties": {
    "userId": {
      "description": "The requesting user",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "fileId": {
      "description": "File ref",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "hearingId": {
      "description": "The hearingId",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "caseId": {
      "description": "The caseId",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "applicationId": {
      "description": "The ApplicationId",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "materialId": {
      "description": "The address4",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "firstClassLetter": {
      "type": "boolean"
    },
    "secondClassLetter": {
      "type": "boolean"
    },
    "emailNotifications": {
      "description": "The email notifications required to be sent for this document",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "http://justice.gov.uk/core/courts/notification/email-channel.json"
      }
    }
  },
  "required": [
    "userId",
    "fileId",
    "hearingId",
    "materialId"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-command/stagingdvla-command-handler/src/raml/json/stagingdvla.command.record-nows-material-request.json
{
  "userId": "42c6c143-c994-4913-9e79-37b418982636",
  "fileId": "42c6c143-c994-4913-9e79-37b418982636",
  "hearingId": "0dd6f629-8a36-4c44-9588-14e7877fa11b",
  "materialId": "0c739c58-9633-4711-82aa-a48ae3aa8f84",
  "caseId": "b4b55110-1d50-11e8-accf-0ed5f89f718b",
  "applicationId": "b4b55110-1d50-11e8-accf-0ed5f89f718b"
}
