=== hmcts/cpp-context-staging-dvla/stagingdvla-event/stagingdvla-event-processor/src/yaml/json/schema/stagingdvla.event.driver-notified.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/cpp/stagingdvla/event/driver-notified.json",
  "description": "The details required to generate a now document",
  "type": "object",
  "properties": {
    "identifier": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "masterDefendantId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "retrySequence": {
      "type": "integer"
    },
    "orderDate": {
      "type": "string",
      "format": "date"
    },
    "amendmentDate": {
      "type": "string",
      "format": "date"
    },
    "convictionDate": {
      "description": "This is attribute is not used , as the convictionDate in subschema defendantCaseOffence is used",
      "type": "string",
      "format": "date"
    },
    "materialId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "orderingHearingId": {
      "description": "The identifier of the hearing that ordered this NOW",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "emailNotifications": {
      "description": "The email notifications required to be sent for this document",
      "type": "array",
      "items": {
        "$ref": "http://justice.gov.uk/core/courts/notification/email-channel.json"
      }
    },
    "orderingCourt": {
      "$ref": "http://justice.gov.uk/core/courts/courtCentre.json"
    },
    "orderingCourtCode": {
      "type": "string"
    },
    "licenceProducedInCourt": {
      "type": "string"
    },
    "defendant": {
      "$ref": "http://justice.gov.uk/core/courts/nowdocument/nowdefendant.json"
    },
    "caseApplicationReferences": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "cases": {
      "title": "cases",
      "type": "array",
      "items": {
        "$ref": "#/definitions/prosecutionCase"
      }
    },
    "courtApplications": {
      "title": "courtApplications",
      "type": "array",
      "items": {
        "$ref": "#/definitions/courtApplication"
      }
    },
    "notificationWasPreviouslySent": {
      "type": "boolean"
    },
    "removedEndorsements": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "updatedEndorsements": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "distinctPrompts": {
      "type": "array",
      "title": "distinctPrompts",
      "items": {
        "$ref": "#/definitions/prompt"
      }
    },
    "previous": {
      "$ref": "#/definitions/now"
    },
    "resetNotificationHistory": {
      "type": "boolean",
      "description": "Indicates that this becomes latest DVLA notification and will be used as orginal for future amendments. This happens when application is amened to refuse DVLA endorsments"
    }
  },
  "required": [
    "orderDate",
    "orderingCourt",
    "defendant",
    "caseApplicationReferences",
    "cases"
  ],
  "definitions": {
    "now": {
      "type": "object",
      "properties": {
        "identifier": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "masterDefendantId": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "retrySequence": {
          "type": "integer"
        },
        "orderDate": {
          "type": "string",
          "format": "date"
        },
        "amendmentDate": {
          "type": "string",
          "format": "date"
        },
        "convictionDate": {
          "type": "string",
          "format": "date"
        },
        "materialId": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "orderingHearingId": {
          "description": "The identifier of the hearing that ordered this NOW",
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "emailNotifications": {
          "description": "The email notifications required to be sent for this document",
          "type": "array",
          "items": {
            "$ref": "http://justice.gov.uk/core/courts/notification/email-channel.json"
          }
        },
        "orderingCourt": {
          "$ref": "http://justice.gov.uk/core/courts/courtCentre.json"
        },
        "licenceProducedInCourt": {
          "type": "string"
        },
        "defendant": {
          "$ref": "http://justice.gov.uk/core/courts/nowdocument/nowdefendant.json"
        },
        "caseApplicationReferences": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "cases": {
          "title": "cases",
          "type": "array",
          "items": {
            "$ref": "#/definitions/prosecutionCase"
          }
        },
        "notificationWasPreviouslySent": {
          "type": "boolean"
        },
        "distinctPrompts": {
          "type": "array",
          "title": "prompts",
          "items": {
            "$ref": "#/definitions/prompt"
          }
        }
      },
      "required": [
        "orderDate",
        "orderingCourt",
        "defendant",
        "caseApplicationReferences",
        "cases"
      ],
      "additionalProperties": false
    },
    "prosecutionCase": {
      "type": "object",
      "properties": {
        "reference": {
          "type": "string"
        },
        "caseId": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "initiationCode": {
          "type": "string"
        },
        "caseStatus": {
          "type": "string"
        },
        "defendantCaseOffences": {
          "type": "array",
          "title": "defendantCaseOffences",
          "items": {
            "$ref": "#/definitions/defendantCaseOffence"
          }
        },
        "hasSV": {
          "type": "boolean"
        }
      },
      "required": [
        "reference",
        "defendantCaseOffences"
      ],
      "additionalProperties": false
    },
    "courtApplication": {
      "type": "object",
      "properties": {
        "applicationReference": {
          "type": "string"
        },
        "applicationStatus": {
          "type": "string"
        },
        "applicationType": {
          "type": "string"
        },
        "applicationTypeId": {
          "type": "string"
        },
        "applicationCode": {
          "type": "string"
        },
        "applicationReceivedDate": {
          "type": "string",
          "format": "date"
        },
        "id": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "results": {
          "type": "array",
          "title": "results",
          "items": {
            "$ref": "#/definitions/result"
          }
        }
      },
      "required": [
        "applicationReference",
        "id"
      ],
      "additionalProperties": false
    },
    "defendantCaseOffence": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "mainOffenceCode": {
          "type": "string"
        },
        "civilOffence": {
          "description": "Indicates that the offence is a civil matter rather than a criminal one",
          "type": "boolean"
        },
        "startDate": {
          "description": "The start date of the offence",
          "type": "string",
          "format": "date"
        },
        "endDate": {
          "description": "The end date of the offence",
          "type": "string",
          "format": "date"
        },
        "convictionDate": {
          "description": "Indicates that prosecution of this offence has led to a criminal conviction.  Not relevant for civil cases",
          "type": "string"
        },
        "convictingCourtCode": {
          "type": "string"
        },
        "convictionStatus": {
          "description": "Indicates the status of a conviction.  Null when offence is civil.  Not Convicted when there is not a conviction date.  Otherwise Convicted",
          "type": "string"
        },
        "plea": {
          "description": "The plea entered against the offence",
          "type": "string"
        },
        "vehicleRegistration": {
          "description": "The vehicle registration relevant to the offence",
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "dvlaCode": {
          "description": "The dvla code for the offence e.g. SP50",
          "type": "string"
        },
        "modeOfTrial": {
          "type": "string"
        },
        "allocationDecision": {
          "type": "string"
        },
        "wording": {
          "type": "string"
        },
        "alcoholReadingAmount": {
          "type": "string"
        },
        "alcoholReadingMethodCode": {
          "type": "string"
        },
        "alcoholReadingMethodDescription": {
          "type": "string"
        },
        "endorsableFlag": {
          "type": "boolean"
        },
        "results": {
          "type": "array",
          "title": "results",
          "items": {
            "$ref": "#/definitions/result"
          }
        },
        "fine": {
          "type": "string"
        },
        "penaltyPoints": {
          "type": "string"
        },
        "disqualificationPeriod": {
          "type": "string"
        },
        "otherSentence": {
          "type": "string"
        },
        "suspendedSentence": {
          "type": "string"
        },
        "dttpDtetp": {
          "type": "string"
        },
        "interimImposedFinalSentence": {
          "type": "string"
        },
        "sentencingCourtCode": {
          "type": "string"
        },
        "sentenceDate": {
          "type": "string",
          "format": "date"
        },
        "dateFromWhichDisqRemoved": {
          "type": "string"
        },
        "dateDisqSuspendedPendingAppeal": {
          "type": "string"
        },
        "dateDisqReimposedFollowingAppeal": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "result": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "resultIdentifier": {
          "type": "string"
        },
        "nowRequirementText": {
          "type": "array",
          "description": "A collection of all the now requirement text items for now requirements associated to the given result",
          "title": "nowRequirementTextItems",
          "items": {
            "$ref": "http://justice.gov.uk/core/courts/nowdocument/now-text.json"
          }
        },
        "publishedForNows": {
          "description": "Determines that when this result published it is published for NOWs only and not for LAA, Court Extract & SPI",
          "type": "boolean"
        },
        "prompts": {
          "type": "array",
          "title": "prompts",
          "items": {
            "$ref": "#/definitions/prompt"
          }
        },
        "resultWording": {
          "type": "string"
        },
        "resultDefinitionGroup": {
          "description": "The result definition group for filtering purposes",
          "type": "string"
        },
        "sequence": {
          "type": "number"
        },
        "d20": {
          "description": "Determines that the result is a D20 result",
          "type": "boolean"
        },
        "pointsDisqualificationCode": {
          "type": "string"
        },
        "drivingTestStipulation": {
          "type": "integer"
        },
        "dvlaCode": {
          "type": "string"
        }
      },
      "required": [
        "label"
      ],
      "additionalProperties": false
    },
    "prompt": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "welshLabel": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "welshValue": {
          "type": "string"
        },
        "promptIdentifier": {
          "type": "string"
        },
        "promptReference": {
          "type": "string"
        },
        "durationSequence": {
          "description": "Determines if the prompt is describing the primary, secondary or tertiary duration in the duration element",
          "type": "number",
          "maximum": 9
        }
      },
      "required": [
        "label"
      ],
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-domain/stagingdvla-domain-aggregate/src/test/resources/testdata/drivernotifications/statdecapp/app-granted-offences-endorsed/case-resulted-events-expected.json
{
  "amendmentDate": "2021-05-20",
  "caseApplicationReferences": [
    "76GD6405821"
  ],
  "cases": [
    {
      "caseId": "8c116550-543f-4eb6-9c5c-29587f66a53d",
      "defendantCaseOffences": [
        {
          "allocationDecision": "Summary-only offence",
          "civilOffence": false,
          "code": "CA03014",
          "convictingCourtCode": "12897",
          "convictionDate": "2021-03-10",
          "convictionStatus": "Convicted",
          "dateFromWhichDisqRemoved": "",
          "dvlaCode": "NE98",
          "endDate": "2005-05-05",
          "endorsableFlag": true,
          "fine": "",
          "interimImposedFinalSentence": "",
          "modeOfTrial": "Summary",
          "otherSentence": "CF",
          "penaltyPoints": "",
          "plea": "INDICATED_GUILTY",
          "results": [
            {
              "d20": true,
              "drivingTestStipulation": 1,
              "dvlaCode": "C",
              "label": "Discretionary disqualification until test passed only",
              "pointsDisqualificationCode": "TT99",
              "publishedForNows": false,
              "resultIdentifier": "cf8a3c59-63f5-4757-8783-88f1e31aa653",
              "resultWording": "Disqualified until test of competence to drive has been passed. Driving record endorsed. Section 36 Road Traffic Offenders Act 1988"
            },
            {
              "d20": true,
              "dvlaCode": "C",
              "label": "Discretionary with disqualification until ordinary test passed. Disqualified for life",
              "prompts": [
                {
                  "durationSequence": 1,
                  "label": "Date of Interim Disqualification",
                  "promptIdentifier": "7fd83833-178c-48db-866b-33fc9e69a0d1",
                  "promptReference": "195a0650-4e22-4ff2-afd3-779e55d9903c",
                  "value": "Starting from date (date of interim disqualification):01/02/2021"
                }
              ],
              "publishedForNows": false,
              "resultIdentifier": "77aeba67-1191-4cd6-9a05-ad2e737c80ec",
              "resultWording": "Disqualified for holding or obtaining a driving licence for life. Discretionary disqualification. Driving record endorsed. Disqualified until test of competence has been passed. Sections 34(2) & 36 Road Traffic Offenders Act 1988"
            }
          ],
          "startDate": "1996-05-04",
          "title": "Fail refuse give assistance to person executing Communications Act search warrant",
          "vehicleRegistration": "TE4654",
          "wording": "Has a violent past and fear that he will commit"
        },
        {
          "code": "CA03014TT99",
          "convictingCourtCode": "12897",
          "convictionDate": "2021-03-10",
          "disqualificationPeriod": "999999",
          "dttpDtetp": "1",
          "dvlaCode": "TT99",
          "mainOffenceCode": "CA03014",
          "wording": "Has a violent past and fear that he will commit"
        }
      ],
      "hasSV": false,
      "initiationCode": "C",
      "reference": "76GD6405821"
    }
  ],
  "courtApplications": [],
  "defendant": {
    "address": {
      "line1": "lLUIfPvz4J",
      "line2": "56Police HouseD",
      "line3": "StreetDescriptionD",
      "line4": "LocalityD",
      "line5": "TownD",
      "postCode": "TW14 9XD"
    },
    "dateOfBirth": "1988-03-07",
    "driverNumber": "MORGA657054SM9BF",
    "firstName": "Robert",
    "gender": "MALE",
    "lastName": "Smith",
    "middleName": "PersonGivenName20A PersonGivenName30A",
    "name": "Robert PersonGivenName20A PersonGivenName30A Smith",
    "title": "YR"
  },
  "distinctPrompts": [],
  "identifier": "9121db0f-21a0-4ed2-a4b8-cc7aad4f384e",
  "masterDefendantId": "bbf80f48-970d-4b2c-8167-f048c719c89a",
  "materialId": "fa043282-7d52-417f-b2c4-61b704adcc86",
  "orderDate": "2021-03-10",
  "orderingCourt": {
    "address": {
      "address1": "176A Lavender Hill",
      "address2": "London",
      "address3": "",
      "address4": "",
      "address5": "",
      "postcode": "SW11 1JU"
    },
    "code": "B01LY00",
    "id": "f8254db1-1683-483e-afb3-b87fde5a0a26",
    "lja": {
      "ljaCode": "2577",
      "ljaName": "South West London Magistrates' Court"
    },
    "name": "Lavender Hill Magistrates' Court",
    "roomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",
    "roomName": "Courtroom 01"
  },
  "orderingCourtCode": "2577",
  "orderingHearingId": "2b9276a1-4285-4838-96b4-461a60a7cb15",
  "retrySequence": 0
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-domain/stagingdvla-domain-aggregate/src/test/resources/testdata/drivernotifications/statdecapp/app-granted-offences-endorsed/ac1/case-resulted-events-expected.json
{
  "caseApplicationReferences": [
    "28DI8690719"
  ],
  "cases": [
    {
      "caseId": "0a5c044a-f0e8-4432-80f3-95a5cb723dc0",
      "caseStatus": "ACTIVE",
      "defendantCaseOffences": [
        {
          "allocationDecision": "Summary-only offence",
          "civilOffence": false,
          "code": "CA03012",
          "convictingCourtCode": "2577",
          "convictionDate": "2025-12-12",
          "convictionStatus": "Convicted",
          "dateFromWhichDisqRemoved": "",
          "disqualificationPeriod": "",
          "dttpDtetp": "",
          "dvlaCode": "NE98",
          "endorsableFlag": false,
          "fine": "",
          "interimImposedFinalSentence": "",
          "modeOfTrial": "Summary",
          "otherSentence": "E06M",
          "penaltyPoints": "6",
          "plea": "GUILTY",
          "results": [
            {
              "d20": false,
              "dvlaCode": "E",
              "label": "Conditional discharge",
              "prompts": [
                {
                  "durationSequence": 1,
                  "label": "PeriodÂ of conditional discharge",
                  "promptIdentifier": "d3205319-84cf-4c5b-9d7a-7e4bb1865054",
                  "promptReference": "periodofConditionalDischarge",
                  "value": "6 Months"
                }
              ],
              "publishedForNows": false,
              "resultIdentifier": "554c2622-c1cc-459e-a98d-b7f317ab065c"
            },
            {
              "d20": true,
              "label": "Driving record endorsed with penalty points",
              "prompts": [
                {
                  "label": "Licence issue number",
                  "promptIdentifier": "11a939b1-71e6-4065-8c29-007e4b52da7a",
                  "promptReference": "licenceIssueNumber",
                  "value": "23"
                },
                {
                  "label": "Penalty points for this offence",
                  "promptIdentifier": "a8719de4-7783-448a-b792-e3f94e670ad0",
                  "promptReference": "PENPT",
                  "value": "6"
                }
              ],
              "publishedForNows": false,
              "resultIdentifier": "cee54856-4450-4f28-a8a9-72b688726201"
            },
            {
              "d20": false,
              "label": "1: Prov DVLA produced",
              "prompts": [
                {
                  "label": "Licence issue number",
                  "promptIdentifier": "11a939b1-71e6-4065-8c29-007e4b52da7a",
                  "promptReference": "licenceIssueNumber",
                  "value": "23"
                }
              ],
              "publishedForNows": true,
              "resultIdentifier": "4b850aa9-984c-4a15-a1ae-b2f861cfcbe8"
            }
          ],
          "startDate": "2022-12-12",
          "title": "Possess / control TV set with intent another use install without a licence",
          "wording": "Napoleon Reichert have set up a TV cable without a valid license."
        }
      ],
      "hasSV": false,
      "initiationCode": "C",
      "reference": "28DI8690719"
    }
  ],
  "courtApplications": [],
  "defendant": {
    "address": {
      "line1": "21",
      "line2": "Furnburry Park Road",
      "line3": "London",
      "postCode": "SW11 3TQ"
    },
    "dateOfBirth": "1991-02-18",
    "firstName": "Napoleon",
    "gender": "MALE",
    "lastName": "Reichert",
    "name": "Napoleon Reichert",
    "title": "MR"
  },
  "distinctPrompts": [
    {
      "label": "Licence issue number",
      "promptIdentifier": "11a939b1-71e6-4065-8c29-007e4b52da7a",
      "promptReference": "licenceIssueNumber",
      "value": "23"
    }
  ],
  "identifier": "39b63ed3-b31c-434e-958e-59803244521b",
  "licenceProducedInCourt": "1: Prov DVLA produced",
  "masterDefendantId": "1fd3d132-e4eb-4c3e-a162-c69a3e3005f4",
  "materialId": "45ddb33d-a9a7-4e45-ba1c-41c4d217f688",
  "orderDate": "2025-12-12",
  "orderingCourt": {
    "address": {
      "address1": "176A Lavender Hill",
      "address2": "London",
      "address3": "",
      "address4": "",
      "address5": "",
      "postcode": "SW11 1JU"
    },
    "code": "B01LY00",
    "courtHearingLocation": "B01LY01",
    "id": "f8254db1-1683-483e-afb3-b87fde5a0a26",
    "lja": {
      "ljaCode": "2577",
      "ljaName": "South West London Magistrates' Court"
    },
    "name": "Lavender Hill Magistrates' Court",
    "roomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",
    "roomName": "Courtroom 01"
  },
  "orderingCourtCode": "2577",
  "orderingHearingId": "29536f9f-fbc2-41b2-9afd-08cc943f7f75",
  "retrySequence": 0
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-domain/stagingdvla-domain-aggregate/src/test/resources/testdata/drivernotifications/statdecapp/app-granted-offences-endorsed/ac1A/case-resulted-events-expected.json
{
  "caseApplicationReferences": [
    "28DI6032316"
  ],
  "cases": [
    {
      "caseId": "8cf054cb-c3b9-4a38-bc09-d7fbb291eabf",
      "caseStatus": "ACTIVE",
      "defendantCaseOffences": [
        {
          "allocationDecision": "Summary-only offence",
          "civilOffence": false,
          "code": "CA03012",
          "convictingCourtCode": "2577",
          "convictionDate": "2025-12-12",
          "convictionStatus": "Convicted",
          "dateFromWhichDisqRemoved": "",
          "disqualificationPeriod": "000600",
          "dttpDtetp": "",
          "dvlaCode": "NE98",
          "endorsableFlag": false,
          "fine": "",
          "interimImposedFinalSentence": "",
          "modeOfTrial": "Summary",
          "otherSentence": "E06M",
          "penaltyPoints": "",
          "plea": "GUILTY",
          "results": [
            {
              "d20": false,
              "dvlaCode": "E",
              "label": "Conditional discharge",
              "prompts": [
                {
                  "durationSequence": 1,
                  "label": "PeriodÂ of conditional discharge",
                  "promptIdentifier": "d3205319-84cf-4c5b-9d7a-7e4bb1865054",
                  "promptReference": "periodofConditionalDischarge",
                  "value": "6 Months"
                }
              ],
              "publishedForNows": false,
              "resultIdentifier": "554c2622-c1cc-459e-a98d-b7f317ab065c"
            },
            {
              "d20": true,
              "label": "Discretionary with ordinary disqualification",
              "prompts": [
                {
                  "label": "Licence issue number",
                  "promptIdentifier": "11a939b1-71e6-4065-8c29-007e4b52da7a",
                  "promptReference": "licenceIssueNumber",
                  "value": "23"
                },
                {
                  "durationSequence": 1,
                  "label": "Disqualification period",
                  "promptIdentifier": "2bf54447-328c-4c1b-a123-341adbd52172",
                  "promptReference": "disqualificationPeriod",
                  "value": "6 Months"
                }
              ],
              "publishedForNows": false,
              "resultIdentifier": "ccfc452e-ebe4-4cd7-b8a0-4f90768447b4",
              "resultWording": "Disqualified for holding or obtaining a driving licence. Discretionary disqualification. Driving record endorsed. Section 34(2) Road Traffic Offenders Act 1988"
            },
            {
              "d20": false,
              "label": "1: Prov DVLA produced",
              "prompts": [
                {
                  "label": "Licence issue number",
                  "promptIdentifier": "11a939b1-71e6-4065-8c29-007e4b52da7a",
                  "promptReference": "licenceIssueNumber",
                  "value": "23"
                }
              ],
              "publishedForNows": true,
              "resultIdentifier": "4b850aa9-984c-4a15-a1ae-b2f861cfcbe8"
            }
          ],
          "startDate": "2022-12-12",
          "title": "Possess / control TV set with intent another use install without a licence",
          "wording": "Roosevelt Wiza have set up a TV cable without a valid license."
        }
      ],
      "hasSV": false,
      "initiationCode": "C",
      "reference": "28DI6032316"
    }
  ],
  "courtApplications": [],
  "defendant": {
    "address": {
      "line1": "21",
      "line2": "Furnburry Park Road",
      "line3": "London",
      "postCode": "SW11 3TQ"
    },
    "dateOfBirth": "1991-02-18",
    "firstName": "Roosevelt",
    "gender": "MALE",
    "lastName": "Wiza",
    "name": "Roosevelt Wiza",
    "title": "MR"
  },
  "distinctPrompts": [
    {
      "label": "Licence issue number",
      "promptIdentifier": "11a939b1-71e6-4065-8c29-007e4b52da7a",
      "promptReference": "licenceIssueNumber",
      "value": "23"
    }
  ],
  "identifier": "1db40ecd-5b89-4561-9507-2172a9be98a2",
  "licenceProducedInCourt": "1: Prov DVLA produced",
  "masterDefendantId": "2a37feb4-0f4f-427d-aab9-bcdc56554089",
  "materialId": "6c2988a7-d7dc-40cb-aa25-13bd39677d72",
  "orderDate": "2025-12-12",
  "orderingCourt": {
    "address": {
      "address1": "176A Lavender Hill",
      "address2": "London",
      "address3": "",
      "address4": "",
      "address5": "",
      "postcode": "SW11 1JU"
    },
    "code": "B01LY00",
    "courtHearingLocation": "B01LY01",
    "id": "f8254db1-1683-483e-afb3-b87fde5a0a26",
    "lja": {
      "ljaCode": "2577",
      "ljaName": "South West London Magistrates' Court"
    },
    "name": "Lavender Hill Magistrates' Court",
    "roomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",
    "roomName": "Courtroom 01"
  },
  "orderingCourtCode": "2577",
  "orderingHearingId": "936644c3-2cac-4b78-bf7a-f03f700fb31d",
  "retrySequence": 0
}
