=== hmcts/cpp-context-staging-dvla/stagingdvla-event/stagingdvla-event-processor/src/yaml/json/schema/stagingdvla.event.driver-notified.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/cpp/stagingdvla/event/driver-notified.json",
  "description": "The details required to generate a now document",
  "type": "object",
  "properties": {
    "identifier": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "masterDefendantId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "retrySequence": {
      "type": "integer"
    },
    "orderDate": {
      "type": "string",
      "format": "date"
    },
    "amendmentDate": {
      "type": "string",
      "format": "date"
    },
    "convictionDate": {
      "description": "This is attribute is not used , as the convictionDate in subschema defendantCaseOffence is used",
      "type": "string",
      "format": "date"
    },
    "materialId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "orderingHearingId": {
      "description": "The identifier of the hearing that ordered this NOW",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "emailNotifications": {
      "description": "The email notifications required to be sent for this document",
      "type": "array",
      "items": {
        "$ref": "http://justice.gov.uk/core/courts/notification/email-channel.json"
      }
    },
    "orderingCourt": {
      "$ref": "http://justice.gov.uk/core/courts/courtCentre.json"
    },
    "orderingCourtCode": {
      "type": "string"
    },
    "licenceProducedInCourt": {
      "type": "string"
    },
    "defendant": {
      "$ref": "http://justice.gov.uk/core/courts/nowdocument/nowdefendant.json"
    },
    "caseApplicationReferences": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "cases": {
      "title": "cases",
      "type": "array",
      "items": {
        "$ref": "#/definitions/prosecutionCase"
      }
    },
    "courtApplications": {
      "title": "courtApplications",
      "type": "array",
      "items": {
        "$ref": "#/definitions/courtApplication"
      }
    },
    "notificationWasPreviouslySent": {
      "type": "boolean"
    },
    "removedEndorsements": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "updatedEndorsements": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "distinctPrompts": {
      "type": "array",
      "title": "distinctPrompts",
      "items": {
        "$ref": "#/definitions/prompt"
      }
    },
    "previous": {
      "$ref": "#/definitions/now"
    },
    "resetNotificationHistory": {
      "type": "boolean",
      "description": "Indicates that this becomes latest DVLA notification and will be used as orginal for future amendments. This happens when application is amened to refuse DVLA endorsments"
    }
  },
  "required": [
    "orderDate",
    "orderingCourt",
    "defendant",
    "caseApplicationReferences",
    "cases"
  ],
  "definitions": {
    "now": {
      "type": "object",
      "properties": {
        "identifier": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "masterDefendantId": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "retrySequence": {
          "type": "integer"
        },
        "orderDate": {
          "type": "string",
          "format": "date"
        },
        "amendmentDate": {
          "type": "string",
          "format": "date"
        },
        "convictionDate": {
          "type": "string",
          "format": "date"
        },
        "materialId": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "orderingHearingId": {
          "description": "The identifier of the hearing that ordered this NOW",
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "emailNotifications": {
          "description": "The email notifications required to be sent for this document",
          "type": "array",
          "items": {
            "$ref": "http://justice.gov.uk/core/courts/notification/email-channel.json"
          }
        },
        "orderingCourt": {
          "$ref": "http://justice.gov.uk/core/courts/courtCentre.json"
        },
        "licenceProducedInCourt": {
          "type": "string"
        },
        "defendant": {
          "$ref": "http://justice.gov.uk/core/courts/nowdocument/nowdefendant.json"
        },
        "caseApplicationReferences": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "cases": {
          "title": "cases",
          "type": "array",
          "items": {
            "$ref": "#/definitions/prosecutionCase"
          }
        },
        "notificationWasPreviouslySent": {
          "type": "boolean"
        },
        "distinctPrompts": {
          "type": "array",
          "title": "prompts",
          "items": {
            "$ref": "#/definitions/prompt"
          }
        }
      },
      "required": [
        "orderDate",
        "orderingCourt",
        "defendant",
        "caseApplicationReferences",
        "cases"
      ],
      "additionalProperties": false
    },
    "prosecutionCase": {
      "type": "object",
      "properties": {
        "reference": {
          "type": "string"
        },
        "caseId": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "initiationCode": {
          "type": "string"
        },
        "caseStatus": {
          "type": "string"
        },
        "defendantCaseOffences": {
          "type": "array",
          "title": "defendantCaseOffences",
          "items": {
            "$ref": "#/definitions/defendantCaseOffence"
          }
        },
        "hasSV": {
          "type": "boolean"
        }
      },
      "required": [
        "reference",
        "defendantCaseOffences"
      ],
      "additionalProperties": false
    },
    "courtApplication": {
      "type": "object",
      "properties": {
        "applicationReference": {
          "type": "string"
        },
        "applicationStatus": {
          "type": "string"
        },
        "applicationType": {
          "type": "string"
        },
        "applicationTypeId": {
          "type": "string"
        },
        "applicationCode": {
          "type": "string"
        },
        "applicationReceivedDate": {
          "type": "string",
          "format": "date"
        },
        "id": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "results": {
          "type": "array",
          "title": "results",
          "items": {
            "$ref": "#/definitions/result"
          }
        }
      },
      "required": [
        "applicationReference",
        "id"
      ],
      "additionalProperties": false
    },
    "defendantCaseOffence": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "mainOffenceCode": {
          "type": "string"
        },
        "civilOffence": {
          "description": "Indicates that the offence is a civil matter rather than a criminal one",
          "type": "boolean"
        },
        "startDate": {
          "description": "The start date of the offence",
          "type": "string",
          "format": "date"
        },
        "endDate": {
          "description": "The end date of the offence",
          "type": "string",
          "format": "date"
        },
        "convictionDate": {
          "description": "Indicates that prosecution of this offence has led to a criminal conviction.  Not relevant for civil cases",
          "type": "string"
        },
        "convictingCourtCode": {
          "type": "string"
        },
        "convictionStatus": {
          "description": "Indicates the status of a conviction.  Null when offence is civil.  Not Convicted when there is not a conviction date.  Otherwise Convicted",
          "type": "string"
        },
        "plea": {
          "description": "The plea entered against the offence",
          "type": "string"
        },
        "vehicleRegistration": {
          "description": "The vehicle registration relevant to the offence",
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "dvlaCode": {
          "description": "The dvla code for the offence e.g. SP50",
          "type": "string"
        },
        "modeOfTrial": {
          "type": "string"
        },
        "allocationDecision": {
          "type": "string"
        },
        "wording": {
          "type": "string"
        },
        "alcoholReadingAmount": {
          "type": "string"
        },
        "alcoholReadingMethodCode": {
          "type": "string"
        },
        "alcoholReadingMethodDescription": {
          "type": "string"
        },
        "endorsableFlag": {
          "type": "boolean"
        },
        "results": {
          "type": "array",
          "title": "results",
          "items": {
            "$ref": "#/definitions/result"
          }
        },
        "fine": {
          "type": "string"
        },
        "penaltyPoints": {
          "type": "string"
        },
        "disqualificationPeriod": {
          "type": "string"
        },
        "otherSentence": {
          "type": "string"
        },
        "suspendedSentence": {
          "type": "string"
        },
        "dttpDtetp": {
          "type": "string"
        },
        "interimImposedFinalSentence": {
          "type": "string"
        },
        "sentencingCourtCode": {
          "type": "string"
        },
        "sentenceDate": {
          "type": "string",
          "format": "date"
        },
        "dateFromWhichDisqRemoved": {
          "type": "string"
        },
        "dateDisqSuspendedPendingAppeal": {
          "type": "string"
        },
        "dateDisqReimposedFollowingAppeal": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "result": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "resultIdentifier": {
          "type": "string"
        },
        "nowRequirementText": {
          "type": "array",
          "description": "A collection of all the now requirement text items for now requirements associated to the given result",
          "title": "nowRequirementTextItems",
          "items": {
            "$ref": "http://justice.gov.uk/core/courts/nowdocument/now-text.json"
          }
        },
        "publishedForNows": {
          "description": "Determines that when this result published it is published for NOWs only and not for LAA, Court Extract & SPI",
          "type": "boolean"
        },
        "prompts": {
          "type": "array",
          "title": "prompts",
          "items": {
            "$ref": "#/definitions/prompt"
          }
        },
        "resultWording": {
          "type": "string"
        },
        "resultDefinitionGroup": {
          "description": "The result definition group for filtering purposes",
          "type": "string"
        },
        "sequence": {
          "type": "number"
        },
        "d20": {
          "description": "Determines that the result is a D20 result",
          "type": "boolean"
        },
        "pointsDisqualificationCode": {
          "type": "string"
        },
        "drivingTestStipulation": {
          "type": "integer"
        },
        "dvlaCode": {
          "type": "string"
        }
      },
      "required": [
        "label"
      ],
      "additionalProperties": false
    },
    "prompt": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "welshLabel": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "welshValue": {
          "type": "string"
        },
        "promptIdentifier": {
          "type": "string"
        },
        "promptReference": {
          "type": "string"
        },
        "durationSequence": {
          "description": "Determines if the prompt is describing the primary, secondary or tertiary duration in the duration element",
          "type": "number",
          "maximum": 9
        }
      },
      "required": [
        "label"
      ],
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-domain/stagingdvla-domain-aggregate/src/test/resources/testdata/drivernotifications/statdecapp/app-granted-offences-endorsed-remove-result/nexh/case-resulted-events-expected.json
{  "caseApplicationReferences": [    "89QB632195"  ],  "cases": [    {      "caseId": "03c77559-d9a8-49c9-8bc3-645a45d6ef99",      "caseStatus": "ACTIVE",      "defendantCaseOffences": [        {          "civilOffence": false,          "code": "TH68023",          "convictionStatus": "Not Convicted",          "dateFromWhichDisqRemoved": "",          "disqualificationPeriod": "",          "dttpDtetp": "",          "dvlaCode": "NE98",          "endorsableFlag": false,          "fine": "",          "interimImposedFinalSentence": "",          "modeOfTrial": "Indictable",          "otherSentence": "E06M",          "penaltyPoints": "",          "results": [            {              "d20": false,              "dvlaCode": "E",              "label": "Conditional discharge",              "prompts": [                {                  "durationSequence": 1,                  "label": "Period of conditional discharge",                  "promptIdentifier": "d3205319-84cf-4c5b-9d7a-7e4bb1865054",                  "promptReference": "periodofConditionalDischarge",                  "value": "6 Months"                }              ],              "publishedForNows": false,              "resultIdentifier": "554c2622-c1cc-459e-a98d-b7f317ab065c"            },            {              "d20": true,              "label": "Driving record endorsed (no points)",              "publishedForNows": false,              "resultIdentifier": "b0aeb4fc-df63-4e2f-af88-97e3f23e847f"            },            {              "d20": false,              "label": "0: None or unknown",              "publishedForNows": true,              "resultIdentifier": "c3a39c2f-b056-442f-8dfc-604b5434f956"            }          ],          "startDate": "2019-11-28",          "title": "Robbery",          "wording": "From 13th November 2018, an aggravated version of this offence applies where the offence is committed against an emergency worker acting in the exercise of his / her functions as such a worker, as per section 1 of the Assaults on emergency Workers (Offences) Act 2018; see offence wording document H19568."        },        {          "civilOffence": false,          "code": "CA03012",          "convictionStatus": "Not Convicted",          "dateFromWhichDisqRemoved": "",          "disqualificationPeriod": "000600",          "dttpDtetp": "",          "dvlaCode": "NE98",          "endorsableFlag": false,          "fine": "",          "interimImposedFinalSentence": "2",          "modeOfTrial": "Summary",          "otherSentence": "E06M",          "penaltyPoints": "",          "results": [            {              "d20": false,              "dvlaCode": "E",              "label": "Conditional discharge",              "prompts": [                {                  "durationSequence": 1,                  "label": "Period of conditional discharge",                  "promptIdentifier": "d3205319-84cf-4c5b-9d7a-7e4bb1865054",                  "promptReference": "periodofConditionalDischarge",                  "value": "6 Months"                }              ],              "publishedForNows": false,              "resultIdentifier": "554c2622-c1cc-459e-a98d-b7f317ab065c"            },            {              "d20": true,              "label": "Discretionary with ordinary disqualification",              "prompts": [                {                  "durationSequence": 1,                  "label": "Disqualification period",                  "promptIdentifier": "2bf54447-328c-4c1b-a123-341adbd52172",                  "promptReference": "disqualificationPeriod",                  "value": "6 Months"                },                {                  "label": "Date of Interim Disqualification",                  "promptIdentifier": "7fd83833-178c-48db-866b-33fc9e69a0d1",                  "promptReference": "600704c8-686a-49d1-b0db-3f67e22553ab",                  "value": "Starting from date (date of interim disqualification):01/06/2026"                }              ],              "publishedForNows": false,              "resultIdentifier": "ccfc452e-ebe4-4cd7-b8a0-4f90768447b4",              "resultWording": "Disqualified for holding or obtaining a driving licence. Discretionary disqualification. Driving record endorsed. Section 34(2) Road Traffic Offenders Act 1988"            },            {              "d20": false,              "label": "Date of Interim Disqualification",              "prompts": [                {                  "label": "Starting from date (date of interim disqualification)",                  "promptIdentifier": "03fe43ad-1857-4ba1-8481-6c660744b617",                  "promptReference": "startingFromDateDateOfInterimDisqualification",                  "value": "01/06/2026"                }              ],              "publishedForNows": true,              "resultIdentifier": "7fd83833-178c-48db-866b-33fc9e69a0d1"            },            {              "d20": false,              "label": "0: None or unknown",              "publishedForNows": true,              "resultIdentifier": "c3a39c2f-b056-442f-8dfc-604b5434f956"            }          ],          "startDate": "2019-11-28",          "title": "Possess / control TV set with intent another use install without a licence",          "wording": "From 13th November 2018, an aggravated version of this offence applies where the offence is committed against an emergency worker acting in the exercise of his / her functions as such a worker, as per section 1 of the Assaults on emergency Workers (Offences) Act 2018; see offence wording document H19568."        }      ],      "hasSV": false,      "initiationCode": "C",      "reference": "89QB632195"    }  ],  "courtApplications": [],  "defendant": {    "address": {      "line1": "799",      "line2": "StreetDescription",      "line3": "Locality2O",      "postCode": "TW14 9XA"    },    "dateOfBirth": "1983-05-14",    "firstName": "Mike1",    "gender": "MALE",    "lastName": "Blick",    "middleName": "Jac ",    "name": "Mike1 Jac  Blick",    "title": "Mr"  },  "distinctPrompts": [],  "identifier": "45eae45e-5fc4-4d08-a735-86404da25bad",  "licenceProducedInCourt": "0: None or unknown",  "masterDefendantId": "7f149498-7ab4-4ea0-b103-1375d31b07f7",  "materialId": "7d457ec3-0538-4873-a13d-0d158bf73d06",  "orderDate": "2025-12-11",  "orderingCourt": {    "address": {      "address1": "176A Lavender Hill",      "address2": "London",      "address3": "",      "address4": "",      "address5": "",      "postcode": "SW11 1JU"    },    "code": "B01LY00",    "courtHearingLocation": "B01LY01",    "id": "f8254db1-1683-483e-afb3-b87fde5a0a26",    "lja": {      "ljaCode": "2577",      "ljaName": "South West London Magistrates' Court"    },    "name": "Lavender Hill Magistrates' Court",    "roomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",    "roomName": "Courtroom 01"  },  "orderingCourtCode": "2577",  "orderingHearingId": "43350a82-0405-42c9-8963-39571712afc6",  "retrySequence": 0}
