=== hmcts/cpp-context-staging-dvla/stagingdvla-command/stagingdvla-command-api/src/raml/json/schema/stagingdvla.command.driver-notification.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/cpp/stagingdvla/command/driver-notification.json",
  "description": "The details required to generate a now document",
  "type": "object",
  "properties": {
    "masterDefendantId": {
      "description": "The master identifier of the defendant that is the subject of this NOW",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "orderingCourt": {
      "$ref": "http://justice.gov.uk/core/courts/courtCentre.json"
    },
    "nowContent": {
      "$ref": "#/definitions/nowDocumentContent"
    },
    "orderingHearingId": {
      "description": "The identifier of the hearing that ordered this NOW",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "isReshare": {
      "type": "boolean"
    }
  },
  "required": [
    "masterDefendantId",
    "orderingCourt",
    "nowContent",
    "orderingHearingId",
    "isReshare"
  ],
  "definitions": {
    "nowDocumentContent": {
      "type": "object",
      "properties": {
        "orderDate": {
          "type": "string",
          "format": "date"
        },
        "amendmentDate": {
          "type": "string",
          "format": "date"
        },
        "defendant": {
          "$ref": "http://justice.gov.uk/core/courts/nowdocument/nowdefendant.json"
        },
        "caseApplicationReferences": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "cases": {
          "title": "cases",
          "type": "array",
          "items": {
            "$ref": "#/definitions/prosecutionCase"
          }
        },
        "courtApplications": {
          "title": "courtApplications",
          "type": "array",
          "items": {
            "$ref": "#/definitions/courtApplication"
          }
        }
      },
      "required": [
        "orderDate",
        "defendant",
        "cases"
      ],
      "additionalProperties": false
    },
    "prosecutionCase": {
      "type": "object",
      "properties": {
        "reference": {
          "type": "string"
        },
        "initiationCode": {
          "type": "string"
        },
        "caseId": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "caseStatus": {
          "type": "string"
        },
        "defendantCaseOffences": {
          "type": "array",
          "title": "defendantCaseOffences",
          "items": {
            "$ref": "#/definitions/defendantCaseOffence"
          }
        }
      },
      "required": [
        "reference",
        "defendantCaseOffences"
      ],
      "additionalProperties": false
    },
    "courtApplication": {
      "type": "object",
      "properties": {
        "applicationReference": {
          "type": "string"
        },
        "applicationStatus": {
          "type": "string"
        },
        "applicationType": {
          "type": "string"
        },
        "applicationTypeId": {
          "type": "string"
        },
        "applicationCode": {
          "type": "string"
        },
        "applicationReceivedDate": {
          "type": "string",
          "format": "date"
        },
        "id": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "results": {
          "type": "array",
          "title": "results",
          "items": {
            "$ref": "#/definitions/result"
          }
        }
      },
      "required": [
        "applicationReference",
        "id"
      ],
      "additionalProperties": false
    },
    "defendantCaseOffence": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "civilOffence": {
          "description": "Indicates that the offence is a civil matter rather than a criminal one",
          "type": "boolean"
        },
        "startDate": {
          "description": "The start date of the offence",
          "type": "string",
          "format": "date"
        },
        "endDate": {
          "description": "The end date of the offence",
          "type": "string",
          "format": "date"
        },
        "convictionDate": {
          "description": "Indicates that prosecution of this offence has led to a criminal conviction.  Not relevant for civil cases",
          "type": "string"
        },
        "convictingCourtCode": {
          "description": "Indicates the code of Convicting court when that prosecution of this offence has led to a criminal conviction. Not relevant for civil cases",
          "type": "string"
        },
        "convictionStatus": {
          "description": "Indicates the status of a conviction.  Null when offence is civil.  Not Convicted when there is not a conviction date.  Otherwise Convicted",
          "type": "string"
        },
        "plea": {
          "description": "The plea entered against the offence",
          "type": "string"
        },
        "vehicleRegistration": {
          "description": "The vehicle registration relevant to the offence",
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "dvlaCode": {
          "description": "The dvla code for the offence e.g. SP50",
          "type": "string"
        },
        "modeOfTrial": {
          "type": "string"
        },
        "allocationDecision": {
          "type": "string"
        },
        "wording": {
          "type": "string"
        },
        "alcoholReadingAmount": {
          "type": "integer"
        },
        "alcoholReadingMethodCode": {
          "type": "string"
        },
        "alcoholReadingMethodDescription": {
          "type": "string"
        },
        "endorsableFlag": {
          "type": "boolean"
        },
        "results": {
          "type": "array",
          "title": "results",
          "items": {
            "$ref": "#/definitions/result"
          }
        }
      },
      "additionalProperties": false
    },
    "result": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "resultIdentifier": {
          "type": "string"
        },
        "nowRequirementText": {
          "type": "array",
          "description": "A collection of all the now requirement text items for now requirements associated to the given result",
          "title": "nowRequirementTextItems",
          "items": {
            "$ref": "http://justice.gov.uk/core/courts/nowdocument/now-text.json"
          }
        },
        "publishedForNows": {
          "description": "Determines that when this result published it is published for NOWs only and not for LAA, Court Extract & SPI",
          "type": "boolean"
        },
        "prompts": {
          "type": "array",
          "title": "prompts",
          "items": {
            "$ref": "#/definitions/prompt"
          }
        },
        "resultWording": {
          "type": "string"
        },
        "resultDefinitionGroup": {
          "description": "The result definition group for filtering purposes",
          "type": "string"
        },
        "sequence": {
          "type": "number"
        },
        "d20": {
          "description": "Determines that the result is a D20 result",
          "type": "boolean"
        },
        "pointsDisqualificationCode": {
          "type": "string"
        },
        "drivingTestStipulation": {
          "type": "integer"
        },
        "dvlaCode": {
          "type": "string"
        },
        "judicialResultCategory": {
          "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/judicialResultCategory"
        }
      },
      "required": [
        "label"
      ],
      "additionalProperties": false
    },
    "prompt": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "welshLabel": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "welshValue": {
          "type": "string"
        },
        "promptIdentifier": {
          "type": "string"
        },
        "promptReference": {
          "type": "string"
        },
        "durationSequence": {
          "description": "Determines if the prompt is describing the primary, secondary or tertiary duration in the duration element",
          "type": "number",
          "maximum": 9
        }
      },
      "required": [
        "label"
      ],
      "additionalProperties": false
    }
  }
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-domain/stagingdvla-domain-aggregate/src/test/resources/testdata/drivernotifications/reopening/dd-40358/ac1/app-resulted.json
{
  "masterDefendantId": "1da3dc44-6e4d-43a7-bfba-745e27da2d7c",
  "orderingCourt": {
    "address": {
      "address1": "Norwich Place",
      "address2": "Bexleyheath",
      "address3": "Kent",
      "address4": "",
      "address5": "",
      "postcode": "DA6 7ND"
    },
    "code": "B01BH00",
    "courtHearingLocation": "B01BH01",
    "id": "7e967376-eacf-4fca-9b30-21b0c5aad427",
    "lja": {
      "ljaCode": "2575",
      "ljaName": "South East London Magistrates' Court"
    },
    "name": "Bexley Magistrates' Court",
    "roomId": "8e912353-3b5d-36c3-953e-ad3b94b19de3",
    "roomName": "Courtroom 01"
  },
  "nowContent": {
    "orderDate": "2026-04-02",
    "defendant": {
      "dateOfBirth": "2005-11-11",
      "gender": "MALE",
      "driverNumber": "VANFL002222OW9PH",
      "title": "Mr",
      "firstName": "Lavinia",
      "lastName": "Marvin",
      "name": "Lavinia Marvin",
      "address": {
        "line1": "9999A9999AAAA",
        "line2": "Woodlane",
        "line3": "addressline 3",
        "line4": "Bristol",
        "line5": "Avon",
        "postCode": "SW11 3TQ"
      }
    },
    "caseApplicationReferences": [
      "28DI3871009"
    ],
    "cases": [
      {
        "caseStatus": "INACTIVE",
        "initiationCode": "C",
        "reference": "28DI3871009",
        "caseId": "40dd59b4-4f02-48f5-b0fa-90eb6c56a00e",
        "defendantCaseOffences": [
          {
            "title": "Conspire to assault a person thereby occasioning them actual bodily harm",
            "civilOffence": false,
            "convictionStatus": "Not Convicted",
            "code": "OF61102C",
            "modeOfTrial": "Indictable",
            "endorsableFlag": false,
            "wording": "Lavinia Marvin at Howell Port, conspired together with Earnest Renner to assault Mack Hahn, thereby occasioning actual bodily harm.",
            "startDate": "2022-12-12",
            "results": [
              {
                "resultIdentifier": "969f150c-cd05-46b0-9dd9-30891efcc766",
                "publishedForNows": false,
                "prompts": [
                  {
                    "promptIdentifier": "7cd1472f-2379-4f5b-9e67-98a43d86e122",
                    "promptReference": "AOF",
                    "label": "Amount of fine",
                    "value": "£200.00"
                  }
                ],
                "resultDefinitionGroup": "Imposition",
                "d20": false,
                "judicialResultCategory": "FINAL",
                "label": "Fine"
              },
              {
                "resultIdentifier": "f121db73-57fb-4f74-9ab1-0843aabe4605",
                "publishedForNows": false,
                "prompts": [
                  {
                    "promptIdentifier": "dcaf502b-44d2-4be0-acfc-2f7d29142da6",
                    "promptReference": "specialReasons",
                    "label": "Special reasons",
                    "value": "tets"
                  }
                ],
                "d20": false,
                "judicialResultCategory": "ANCILLARY",
                "label": "No endorsement - Special Reasons"
              },
              {
                "resultIdentifier": "a0b426c1-74b8-43cd-9885-f0f31625352e",
                "publishedForNows": false,
                "prompts": [
                  {
                    "promptIdentifier": "ee7d253a-c629-11e8-a355-529269fb1459",
                    "promptReference": "PBD",
                    "label": "Date to pay in full by",
                    "value": "03/03/2028"
                  }
                ],
                "resultDefinitionGroup": "Payment terms",
                "d20": false,
                "judicialResultCategory": "ANCILLARY",
                "label": "Payment terms - on release"
              }
            ]
          },
          {
            "title": "Public service vehicles - passenger failing to pay fare",
            "civilOffence": false,
            "convictionStatus": "Not Convicted",
            "code": "PS90015",
            "modeOfTrial": "Summary",
            "endorsableFlag": false,
            "wording": "Public service vehicles - passenger failing to pay fare",
            "startDate": "2022-11-28",
            "results": [
              {
                "resultIdentifier": "969f150c-cd05-46b0-9dd9-30891efcc766",
                "publishedForNows": false,
                "prompts": [
                  {
                    "promptIdentifier": "7cd1472f-2379-4f5b-9e67-98a43d86e122",
                    "promptReference": "AOF",
                    "label": "Amount of fine",
                    "value": "£250.00"
                  }
                ],
                "resultDefinitionGroup": "Imposition",
                "d20": false,
                "judicialResultCategory": "FINAL",
                "label": "Fine"
              },
              {
                "resultIdentifier": "f121db73-57fb-4f74-9ab1-0843aabe4605",
                "publishedForNows": false,
                "prompts": [
                  {
                    "promptIdentifier": "dcaf502b-44d2-4be0-acfc-2f7d29142da6",
                    "promptReference": "specialReasons",
                    "label": "Special reasons",
                    "value": "test"
                  }
                ],
                "d20": false,
                "judicialResultCategory": "ANCILLARY",
                "label": "No endorsement - Special Reasons"
              }
            ]
          },
          {
            "title": "Robbery",
            "civilOffence": false,
            "convictionStatus": "Not Convicted",
            "code": "TH68023",
            "modeOfTrial": "Indictable",
            "endorsableFlag": false,
            "wording": "From 13th November 2018, an aggravated version of this offence applies where the offence is committed against an emergency worker acting in the exercise of his / her functions as such a worker, as per section 1 of the Assaults on emergency Workers (Offences) Act 2018; see offence wording document H19568.",
            "startDate": "2019-11-28",
            "results": [
              {
                "resultIdentifier": "554c2622-c1cc-459e-a98d-b7f317ab065c",
                "publishedForNows": false,
                "prompts": [
                  {
                    "promptIdentifier": "d3205319-84cf-4c5b-9d7a-7e4bb1865054",
                    "promptReference": "periodofConditionalDischarge",
                    "durationSequence": 1,
                    "label": "Period of conditional discharge",
                    "value": "12 Months"
                  }
                ],
                "d20": false,
                "dvlaCode": "E",
                "judicialResultCategory": "FINAL",
                "label": "Conditional discharge"
              }
            ]
          }
        ]
      }
    ],
    "courtApplications": [
      {
        "applicationType": "Application to reopen case",
        "applicationTypeId": "9d2ae0fe-d4d0-43ca-ab7a-7a2556cafe5e",
        "applicationReceivedDate": "2026-04-01",
        "id": "37907da8-0836-4a66-9f7b-fc840798674e",
        "applicationReference": "28DI3871009",
        "applicationStatus": "FINALISED",
        "results": [
          {
            "resultIdentifier": "2b3f7c20-8fc1-4fad-9076-df196c24b27e",
            "publishedForNows": false,
            "d20": false,
            "judicialResultCategory": "FINAL",
            "label": "Granted"
          },
          {
            "resultIdentifier": "e3fb46ee-e406-4f73-9bf1-71d513da8cc7",
            "publishedForNows": false,
            "prompts": [
              {
                "promptIdentifier": "3872ea68-92d9-469f-9929-c676745982ef",
                "promptReference": "reopenedUnder",
                "label": "Re-opened under",
                "value": "Section 155 Powers of Criminal Courts (Sentencing) Act 2000"
              },
              {
                "promptIdentifier": "5797feb0-7678-4193-ad16-944365e9a68a",
                "promptReference": "convictionAndSentenceImposedOnSpecifiedDateAreSetAside",
                "label": "Conviction and sentence imposed on specified date are set aside",
                "value": "03/03/2027"
              },
              {
                "promptIdentifier": "0a7dd6aa-f7cc-43d7-ba03-c9621f3e4471",
                "promptReference": "prosecutortobenotifiedOrganisationName",
                "label": "Prosecutor to be notified organisation name",
                "value": "test"
              },
              {
                "promptIdentifier": "0a7dd6aa-f7cc-43d7-ba03-c9621f3e4471",
                "promptReference": "prosecutortobenotifiedAddress1",
                "label": "Prosecutor to be notified address line 1",
                "value": "test"
              },
              {
                "promptIdentifier": "0a7dd6aa-f7cc-43d7-ba03-c9621f3e4471",
                "promptReference": "prosecutortobenotifiedPostCode",
                "label": "Prosecutor to be notified post code",
                "value": "MK6 7AS"
              }
            ],
            "d20": false,
            "judicialResultCategory": "FINAL",
            "label": "Case reopened"
          }
        ]
      }
    ]
  },
  "isReshare": false,
  "orderingHearingId": "791384d8-b6fb-4d01-a735-23826b08463e"
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-domain/stagingdvla-domain-aggregate/src/test/resources/testdata/drivernotifications/reopening/dd-39832/ac2/app-resulted.json
{
  "masterDefendantId": "9f8b4c1f-a6cb-4ad7-b1ae-c85d034beb96",
  "orderingCourt": {
    "address": {
      "address1": "The Magistrates' Court",
      "address2": "Barclay Road",
      "address3": "Croydon",
      "address4": "",
      "address5": "",
      "postcode": "CR9 3NG"
    },
    "code": "B01EF00",
    "courtHearingLocation": "B01EF01",
    "id": "31b3d313-7a7c-4598-bb4b-c1bff9b00e26",
    "lja": {
      "ljaCode": "2576",
      "ljaName": "South London Magistrates' Court"
    },
    "name": "Croydon Magistrates' Court",
    "roomId": "bfb67c13-789c-373b-b442-52b82faf863e",
    "roomName": "Courtroom 01"
  },
  "nowContent": {
    "orderDate": "2026-03-25",
    "defendant": {
      "dateOfBirth": "2005-11-11",
      "gender": "MALE",
      "driverNumber": "VANFL002222OW9PH",
      "title": "Mr",
      "firstName": "Ana",
      "lastName": "Dickens",
      "name": "Ana Dickens",
      "address": {
        "line1": "9999A9999AAAA",
        "line2": "Woodlane",
        "line3": "addressline 3",
        "line4": "Bristol",
        "line5": "Avon",
        "postCode": "SW11 3TQ"
      }
    },
    "caseApplicationReferences": [
      "28DI7705233"
    ],
    "cases": [
      {
        "caseStatus": "INACTIVE",
        "initiationCode": "C",
        "reference": "28DI7705233",
        "caseId": "3b9c0358-9010-4871-a8b8-474fd7ecc1df",
        "defendantCaseOffences": [
          {
            "title": "Conspire to assault a person thereby occasioning them actual bodily harm",
            "civilOffence": false,
            "convictionStatus": "Not Convicted",
            "code": "OF61102C",
            "modeOfTrial": "Indictable",
            "endorsableFlag": false,
            "wording": "Ana Dickens at Audreanne Manors, conspired together with Luz Brown to assault Allen Spencer, thereby occasioning actual bodily harm.",
            "startDate": "2022-12-12",
            "results": [
              {
                "resultIdentifier": "3e859586-bc86-407d-bd8e-c9a01d40d147",
                "publishedForNows": false,
                "d20": false,
                "label": "Offence not dealt with as part of application - original adjudication to stand"
              }
            ]
          },
          {
            "title": "Public service vehicles - passenger failing to pay fare",
            "civilOffence": false,
            "convictionStatus": "Not Convicted",
            "code": "PS90015",
            "modeOfTrial": "Summary",
            "endorsableFlag": false,
            "wording": "Public service vehicles - passenger failing to pay fare",
            "startDate": "2022-11-28",
            "results": [
              {
                "resultIdentifier": "3e859586-bc86-407d-bd8e-c9a01d40d147",
                "publishedForNows": false,
                "d20": false,
                "label": "Offence not dealt with as part of application - original adjudication to stand"
              }
            ]
          },
          {
            "title": "Robbery",
            "civilOffence": false,
            "convictionStatus": "Not Convicted",
            "code": "TH68023",
            "modeOfTrial": "Indictable",
            "endorsableFlag": false,
            "wording": "From 13th November 2018, an aggravated version of this offence applies where the offence is committed against an emergency worker acting in the exercise of his / her functions as such a worker, as per section 1 of the Assaults on emergency Workers (Offences) Act 2018; see offence wording document H19568.",
            "startDate": "2019-11-28",
            "results": [
              {
                "resultIdentifier": "554c2622-c1cc-459e-a98d-b7f317ab065c",
                "publishedForNows": false,
                "prompts": [
                  {
                    "promptIdentifier": "d3205319-84cf-4c5b-9d7a-7e4bb1865054",
                    "promptReference": "periodofConditionalDischarge",
                    "durationSequence": 1,
                    "label": "Period of conditional discharge",
                    "value": "12 Months"
                  }
                ],
                "d20": false,
                "dvlaCode": "E",
                "label": "Conditional discharge"
              }
            ]
          }
        ]
      }
    ],
    "courtApplications": [
      {
        "applicationType": "Application to reopen case",
        "applicationTypeId": "9d2ae0fe-d4d0-43ca-ab7a-7a2556cafe5e",
        "applicationReceivedDate": "2026-03-24",
        "id": "393a5303-72a9-4809-8bb8-bb1f64ef91e5",
        "applicationReference": "28DI7705233",
        "applicationStatus": "FINALISED",
        "results": [
          {
            "resultIdentifier": "2b3f7c20-8fc1-4fad-9076-df196c24b27e",
            "publishedForNows": false,
            "d20": false,
            "label": "Granted"
          },
          {
            "resultIdentifier": "e3fb46ee-e406-4f73-9bf1-71d513da8cc7",
            "publishedForNows": false,
            "prompts": [
              {
                "promptIdentifier": "3872ea68-92d9-469f-9929-c676745982ef",
                "promptReference": "reopenedUnder",
                "label": "Re-opened under",
                "value": "Section 142 Magistrates' Courts Act 1980"
              },
              {
                "promptIdentifier": "5797feb0-7678-4193-ad16-944365e9a68a",
                "promptReference": "convictionAndSentenceImposedOnSpecifiedDateAreSetAside",
                "label": "Conviction and sentence imposed on specified date are set aside",
                "value": "02/02/2023"
              },
              {
                "promptIdentifier": "0a7dd6aa-f7cc-43d7-ba03-c9621f3e4471",
                "promptReference": "prosecutortobenotifiedOrganisationName",
                "label": "Prosecutor to be notified organisation name",
                "value": "test"
              },
              {
                "promptIdentifier": "0a7dd6aa-f7cc-43d7-ba03-c9621f3e4471",
                "promptReference": "prosecutortobenotifiedAddress1",
                "label": "Prosecutor to be notified address line 1",
                "value": "test 1"
              },
              {
                "promptIdentifier": "0a7dd6aa-f7cc-43d7-ba03-c9621f3e4471",
                "promptReference": "prosecutortobenotifiedPostCode",
                "label": "Prosecutor to be notified post code",
                "value": "Mk4 4SG"
              }
            ],
            "d20": false,
            "label": "Case reopened"
          }
        ]
      }
    ]
  },
  "isReshare": false,
  "orderingHearingId": "e5e8d3c6-784f-463f-bc87-c380f57c170a"
}
