=== hmcts/cpp-context-staging-dvla/stagingdvla-command/stagingdvla-command-api/src/raml/json/schema/stagingdvla.command.driver-notification.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/cpp/stagingdvla/command/driver-notification.json",
  "description": "The details required to generate a now document",
  "type": "object",
  "properties": {
    "masterDefendantId": {
      "description": "The master identifier of the defendant that is the subject of this NOW",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "orderingCourt": {
      "$ref": "http://justice.gov.uk/core/courts/courtCentre.json"
    },
    "nowContent": {
      "$ref": "#/definitions/nowDocumentContent"
    },
    "orderingHearingId": {
      "description": "The identifier of the hearing that ordered this NOW",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "isReshare": {
      "type": "boolean"
    }
  },
  "required": [
    "masterDefendantId",
    "orderingCourt",
    "nowContent",
    "orderingHearingId",
    "isReshare"
  ],
  "definitions": {
    "nowDocumentContent": {
      "type": "object",
      "properties": {
        "orderDate": {
          "type": "string",
          "format": "date"
        },
        "amendmentDate": {
          "type": "string",
          "format": "date"
        },
        "defendant": {
          "$ref": "http://justice.gov.uk/core/courts/nowdocument/nowdefendant.json"
        },
        "caseApplicationReferences": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "cases": {
          "title": "cases",
          "type": "array",
          "items": {
            "$ref": "#/definitions/prosecutionCase"
          }
        },
        "courtApplications": {
          "title": "courtApplications",
          "type": "array",
          "items": {
            "$ref": "#/definitions/courtApplication"
          }
        }
      },
      "required": [
        "orderDate",
        "defendant",
        "cases"
      ],
      "additionalProperties": false
    },
    "prosecutionCase": {
      "type": "object",
      "properties": {
        "reference": {
          "type": "string"
        },
        "initiationCode": {
          "type": "string"
        },
        "caseId": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "caseStatus": {
          "type": "string"
        },
        "defendantCaseOffences": {
          "type": "array",
          "title": "defendantCaseOffences",
          "items": {
            "$ref": "#/definitions/defendantCaseOffence"
          }
        }
      },
      "required": [
        "reference",
        "defendantCaseOffences"
      ],
      "additionalProperties": false
    },
    "courtApplication": {
      "type": "object",
      "properties": {
        "applicationReference": {
          "type": "string"
        },
        "applicationStatus": {
          "type": "string"
        },
        "applicationType": {
          "type": "string"
        },
        "applicationTypeId": {
          "type": "string"
        },
        "applicationCode": {
          "type": "string"
        },
        "applicationReceivedDate": {
          "type": "string",
          "format": "date"
        },
        "id": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "results": {
          "type": "array",
          "title": "results",
          "items": {
            "$ref": "#/definitions/result"
          }
        }
      },
      "required": [
        "applicationReference",
        "id"
      ],
      "additionalProperties": false
    },
    "defendantCaseOffence": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "civilOffence": {
          "description": "Indicates that the offence is a civil matter rather than a criminal one",
          "type": "boolean"
        },
        "startDate": {
          "description": "The start date of the offence",
          "type": "string",
          "format": "date"
        },
        "endDate": {
          "description": "The end date of the offence",
          "type": "string",
          "format": "date"
        },
        "convictionDate": {
          "description": "Indicates that prosecution of this offence has led to a criminal conviction.  Not relevant for civil cases",
          "type": "string"
        },
        "convictingCourtCode": {
          "description": "Indicates the code of Convicting court when that prosecution of this offence has led to a criminal conviction. Not relevant for civil cases",
          "type": "string"
        },
        "convictionStatus": {
          "description": "Indicates the status of a conviction.  Null when offence is civil.  Not Convicted when there is not a conviction date.  Otherwise Convicted",
          "type": "string"
        },
        "plea": {
          "description": "The plea entered against the offence",
          "type": "string"
        },
        "vehicleRegistration": {
          "description": "The vehicle registration relevant to the offence",
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "dvlaCode": {
          "description": "The dvla code for the offence e.g. SP50",
          "type": "string"
        },
        "modeOfTrial": {
          "type": "string"
        },
        "allocationDecision": {
          "type": "string"
        },
        "wording": {
          "type": "string"
        },
        "alcoholReadingAmount": {
          "type": "integer"
        },
        "alcoholReadingMethodCode": {
          "type": "string"
        },
        "alcoholReadingMethodDescription": {
          "type": "string"
        },
        "endorsableFlag": {
          "type": "boolean"
        },
        "results": {
          "type": "array",
          "title": "results",
          "items": {
            "$ref": "#/definitions/result"
          }
        }
      },
      "additionalProperties": false
    },
    "result": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "resultIdentifier": {
          "type": "string"
        },
        "nowRequirementText": {
          "type": "array",
          "description": "A collection of all the now requirement text items for now requirements associated to the given result",
          "title": "nowRequirementTextItems",
          "items": {
            "$ref": "http://justice.gov.uk/core/courts/nowdocument/now-text.json"
          }
        },
        "publishedForNows": {
          "description": "Determines that when this result published it is published for NOWs only and not for LAA, Court Extract & SPI",
          "type": "boolean"
        },
        "prompts": {
          "type": "array",
          "title": "prompts",
          "items": {
            "$ref": "#/definitions/prompt"
          }
        },
        "resultWording": {
          "type": "string"
        },
        "resultDefinitionGroup": {
          "description": "The result definition group for filtering purposes",
          "type": "string"
        },
        "sequence": {
          "type": "number"
        },
        "d20": {
          "description": "Determines that the result is a D20 result",
          "type": "boolean"
        },
        "pointsDisqualificationCode": {
          "type": "string"
        },
        "drivingTestStipulation": {
          "type": "integer"
        },
        "dvlaCode": {
          "type": "string"
        },
        "judicialResultCategory": {
          "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/judicialResultCategory"
        }
      },
      "required": [
        "label"
      ],
      "additionalProperties": false
    },
    "prompt": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "welshLabel": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "welshValue": {
          "type": "string"
        },
        "promptIdentifier": {
          "type": "string"
        },
        "promptReference": {
          "type": "string"
        },
        "durationSequence": {
          "description": "Determines if the prompt is describing the primary, secondary or tertiary duration in the duration element",
          "type": "number",
          "maximum": 9
        }
      },
      "required": [
        "label"
      ],
      "additionalProperties": false
    }
  }
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-domain/stagingdvla-domain-aggregate/src/test/resources/testdata/drivernotifications/reopening/dd-39832/ac3/app-resulted.json
{
  "masterDefendantId": "4da0a1c6-c0a9-49d8-9226-b5f560947de5",
  "orderingCourt": {
    "address": {
      "address1": "The Magistrates' Court",
      "address2": "Barclay Road",
      "address3": "Croydon",
      "address4": "",
      "address5": "",
      "postcode": "CR9 3NG"
    },
    "code": "B01EF00",
    "courtHearingLocation": "B01EF01",
    "id": "31b3d313-7a7c-4598-bb4b-c1bff9b00e26",
    "lja": {
      "ljaCode": "2576",
      "ljaName": "South London Magistrates' Court"
    },
    "name": "Croydon Magistrates' Court",
    "roomId": "bfb67c13-789c-373b-b442-52b82faf863e",
    "roomName": "Courtroom 01"
  },
  "nowContent": {
    "orderDate": "2026-03-25",
    "defendant": {
      "dateOfBirth": "2005-11-11",
      "gender": "MALE",
      "driverNumber": "VANFL002222OW9PH",
      "title": "Mr",
      "firstName": "Else",
      "lastName": "Brown",
      "name": "Else Brown",
      "address": {
        "line1": "9999A9999AAAA",
        "line2": "Woodlane",
        "line3": "addressline 3",
        "line4": "Bristol",
        "line5": "Avon",
        "postCode": "SW11 3TQ"
      }
    },
    "caseApplicationReferences": [
      "28DI1149025"
    ],
    "cases": [
      {
        "caseStatus": "INACTIVE",
        "initiationCode": "C",
        "reference": "28DI1149025",
        "caseId": "de7368e9-58e8-4fe1-bde4-4239d61d7e33",
        "defendantCaseOffences": [
          {
            "title": "Conspire to assault a person thereby occasioning them actual bodily harm",
            "civilOffence": false,
            "convictionStatus": "Not Convicted",
            "code": "OF61102C",
            "modeOfTrial": "Indictable",
            "endorsableFlag": false,
            "wording": "Else Brown at Sally Lodge, conspired together with Ms. Patrick Ortiz to assault Josh Parisian DDS, thereby occasioning actual bodily harm.",
            "startDate": "2022-12-12",
            "results": [
              {
                "resultIdentifier": "3e859586-bc86-407d-bd8e-c9a01d40d147",
                "publishedForNows": false,
                "d20": false,
                "label": "Offence not dealt with as part of application - original adjudication to stand"
              }
            ]
          },
          {
            "title": "Public service vehicles - passenger failing to pay fare",
            "civilOffence": false,
            "convictionStatus": "Not Convicted",
            "code": "PS90015",
            "modeOfTrial": "Summary",
            "endorsableFlag": false,
            "wording": "Public service vehicles - passenger failing to pay fare",
            "startDate": "2022-11-28",
            "results": [
              {
                "resultIdentifier": "3e859586-bc86-407d-bd8e-c9a01d40d147",
                "publishedForNows": false,
                "d20": false,
                "label": "Offence not dealt with as part of application - original adjudication to stand"
              }
            ]
          },
          {
            "title": "Robbery",
            "civilOffence": false,
            "convictionStatus": "Not Convicted",
            "code": "TH68023",
            "modeOfTrial": "Indictable",
            "endorsableFlag": false,
            "wording": "From 13th November 2018, an aggravated version of this offence applies where the offence is committed against an emergency worker acting in the exercise of his / her functions as such a worker, as per section 1 of the Assaults on emergency Workers (Offences) Act 2018; see offence wording document H19568.",
            "startDate": "2019-11-28",
            "results": [
              {
                "resultIdentifier": "b0aeb4fc-df63-4e2f-af88-97e3f23e847f",
                "publishedForNows": false,
                "d20": true,
                "label": "Driving record endorsed (no points)"
              },
              {
                "resultIdentifier": "c3a39c2f-b056-442f-8dfc-604b5434f956",
                "publishedForNows": true,
                "d20": false,
                "label": "0: None or unknown"
              }
            ]
          }
        ]
      }
    ],
    "courtApplications": [
      {
        "applicationType": "Application to reopen case",
        "applicationTypeId": "9d2ae0fe-d4d0-43ca-ab7a-7a2556cafe5e",
        "applicationReceivedDate": "2026-03-24",
        "id": "efa213e9-08a6-4621-9808-d5b4543ac7a0",
        "applicationReference": "28DI1149025",
        "applicationStatus": "FINALISED",
        "results": [
          {
            "resultIdentifier": "2b3f7c20-8fc1-4fad-9076-df196c24b27e",
            "publishedForNows": false,
            "d20": false,
            "label": "Granted"
          },
          {
            "resultIdentifier": "e3fb46ee-e406-4f73-9bf1-71d513da8cc7",
            "publishedForNows": false,
            "prompts": [
              {
                "promptIdentifier": "3872ea68-92d9-469f-9929-c676745982ef",
                "promptReference": "reopenedUnder",
                "label": "Re-opened under",
                "value": "Section 142 Magistrates' Courts Act 1980"
              },
              {
                "promptIdentifier": "5797feb0-7678-4193-ad16-944365e9a68a",
                "promptReference": "convictionAndSentenceImposedOnSpecifiedDateAreSetAside",
                "label": "Conviction and sentence imposed on specified date are set aside",
                "value": "06/06/2026"
              },
              {
                "promptIdentifier": "0a7dd6aa-f7cc-43d7-ba03-c9621f3e4471",
                "promptReference": "prosecutortobenotifiedOrganisationName",
                "label": "Prosecutor to be notified organisation name",
                "value": "test"
              },
              {
                "promptIdentifier": "0a7dd6aa-f7cc-43d7-ba03-c9621f3e4471",
                "promptReference": "prosecutortobenotifiedAddress1",
                "label": "Prosecutor to be notified address line 1",
                "value": "test"
              },
              {
                "promptIdentifier": "0a7dd6aa-f7cc-43d7-ba03-c9621f3e4471",
                "promptReference": "prosecutortobenotifiedPostCode",
                "label": "Prosecutor to be notified post code",
                "value": "MK3 5GH"
              }
            ],
            "d20": false,
            "label": "Case reopened"
          }
        ]
      }
    ]
  },
  "isReshare": false,
  "orderingHearingId": "a89367d5-d3ff-4725-8556-664662169aed"
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-integration-test/src/test/resources/appealAmendReshare/scenario7/command2.json
{
  "masterDefendantId": "%DEFENDANT_ID%",
  "orderingCourt": {
    "address": {
      "address1": "176A Lavender Hill",
      "address2": "London",
      "address3": "",
      "address4": "",
      "address5": "",
      "postcode": "SW11 1JU"
    },
    "code": "B01LY00",
    "courtHearingLocation": "B01LY01",
    "id": "f8254db1-1683-483e-afb3-b87fde5a0a26",
    "lja": {
      "ljaCode": "2577",
      "ljaName": "South West London Magistrates' Court"
    },
    "name": "Lavender Hill Magistrates' Court",
    "roomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",
    "roomName": "Courtroom 01"
  },
  "nowContent": {
    "orderDate": "2023-05-05",
    "defendant": {
      "dateOfBirth": "2000-09-09",
      "gender": "MALE",
      "driverNumber": "ABCDE0,0010BCFAA",
      "title": "MR",
      "firstName": "Jazmyn",
      "middleName": "Jasmine Jasmine",
      "lastName": "Terry",
      "name": "Jazmyn Jasmine Jasmine Terry",
      "address": {
        "line1": "56saon",
        "line2": "56Police House",
        "line3": "StreetDescription1",
        "line4": "Locality1",
        "line5": "Janechester",
        "postCode": "TW14 9XJ"
      }
    },
    "caseApplicationReferences": [
      "JW98466038"
    ],
    "cases": [
      {
        "reference": "JW98466038",
        "caseId": "5e7683eb-74d1-4748-bb7c-85422c4d3307",
        "defendantCaseOffences": [
          {
            "title": "Drive motor vehicle fail comply with red / green arrow / lane closure traffic light signals - manual detection",
            "civilOffence": false,
            "dvlaCode": "TS10",
            "endDate": "2020-09-17",
            "convictionStatus": "Not Convicted",
            "vehicleRegistration": "TE4654",
            "alcoholReadingAmount": 500,
            "alcoholReadingMethodCode": "A",
            "alcoholReadingMethodDescription": "Blood",
            "code": "RT88971",
            "modeOfTrial": "Summary",
            "endorsableFlag": true,
            "wording": "Has a violent past and fear that he will commit further offences and interfere with witnesse",
            "startDate": "2020-09-18",
            "results": [
              {
                "resultIdentifier": "cee54856-4450-4f28-a8a9-72b688726201",
                "publishedForNows": false,
                "prompts": [
                  {
                    "promptIdentifier": "a8719de4-7783-448a-b792-e3f94e670ad0",
                    "promptReference": "PENPT",
                    "label": "Penalty points for this offence",
                    "value": "6"
                  },
                  {
                    "promptIdentifier": "a593ae4a-9d69-45b9-9585-c11aeed28404",
                    "promptReference": "defendantDrivingLicenceNumber",
                    "label": "Defendant driving licence number",
                    "value": "ABCDE0,0010BCFAA"
                  }
                ],
                "d20": true,
                "label": "Driving record endorsed with penalty points"
              },
              {
                "resultIdentifier": "b9c6047b-fb84-4b12-97a1-2175e4b8bbac",
                "publishedForNows": false,
                "resultWording": "",
                "d20": false,
                "dvlaCode": "J",
                "label": "Absolute discharge"
              },
              {
                "resultIdentifier": "55f15ecf-ea80-40f4-848d-29e7b8d73ae2",
                "publishedForNows": false,
                "prompts": [
                  {
                    "promptIdentifier": "80dd4486-fa86-41f0-b09b-bad84b55f61c",
                    "promptReference": "CADATE",
                    "label": "Date appeal heard",
                    "value": "05/05/2023"
                  }
                ],
                "d20": false,
                "label": "Sentence varied"
              }
            ]
          }
        ]
      }
    ],
    "courtApplications": [
      {
        "applicationType": "Appeal against sentence by a Magistrates' Court to the Crown Court",
        "applicationReceivedDate": "2023-05-05",
        "id": "ec1e74d7-3584-44e2-ab05-37bc10d216e6",
        "applicationReference": "JW98466038",
        "applicationStatus": "UN_ALLOCATED",
        "results": [
          {
            "resultIdentifier": "d861586a-df88-440d-98d4-63cc2a680ae1",
            "publishedForNows": false,
            "prompts": [
              {
                "promptIdentifier": "c946a5df-5849-4cca-b425-ecbd6bd704dc",
                "promptReference": "dateSentenceWasImposed",
                "label": "Date sentence was imposed",
                "value": "05/05/2023"
              },
              {
                "promptIdentifier": "c10b4c83-1856-4ca9-9592-d8b8183a0324",
                "promptReference": "reasons",
                "label": "Reasons",
                "value": "Test"
              }
            ],
            "resultWording": "",
            "d20": false,
            "label": "Appeal against sentence allowed"
          }
        ]
      }
    ]
  },
  "isReshare": true,
  "orderingHearingId": "c7913573-c44d-4292-bce4-d4e52c5104c4"
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-integration-test/src/test/resources/matchedDefendantDifferentHearing/scenario5/command3.json
{
  "masterDefendantId": "%DEFENDANT_ID%",
  "orderingCourt": {
    "address": {
      "address1": "176A Lavender Hill",
      "address2": "London",
      "address3": "",
      "address4": "",
      "address5": "",
      "postcode": "SW11 1JU"
    },
    "code": "B01LY00",
    "courtHearingLocation": "B01LY01",
    "id": "f8254db1-1683-483e-afb3-b87fde5a0a26",
    "lja": {
      "ljaCode": "2577",
      "ljaName": "South West London Magistrates' Court"
    },
    "name": "Lavender Hill Magistrates' Court",
    "roomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",
    "roomName": "Courtroom 01"
  },
  "nowContent": {
    "orderDate": "2023-04-23",
    "defendant": {
      "dateOfBirth": "1985-08-14",
      "gender": "MALE",
      "driverNumber": "ABCDE0,0010BCFAA",
      "title": "MR",
      "firstName": "Claude",
      "middleName": "Jasmine Jasmine",
      "lastName": "EVERTON",
      "name": "Claude Jasmine Jasmine EVERTON",
      "address": {
        "line1": "56saon",
        "line2": "56Police House",
        "line3": "StreetDescription1",
        "line4": "Locality1",
        "line5": "Leeds",
        "postCode": "TW13 4AA"
      }
    },
    "caseApplicationReferences": [
      "JW169482597"
    ],
    "cases": [
      {
        "reference": "JW169482597",
        "caseId": "8f62c81d-9610-4234-a915-c4132d369bcf",
        "defendantCaseOffences": [
          {
            "title": "Cause use of motor vehicle with no insurance",
            "civilOffence": false,
            "dvlaCode": "IN14",
            "endDate": "2020-09-17",
            "convictionDate": "2023-04-23",
            "convictionStatus": "Convicted",
            "plea": "GUILTY",
            "vehicleRegistration": "TE4654",
            "alcoholReadingAmount": 500,
            "alcoholReadingMethodCode": "A",
            "alcoholReadingMethodDescription": "Blood",
            "code": "RT88319",
            "modeOfTrial": "Summary",
            "allocationDecision": "Summary-only offence",
            "endorsableFlag": true,
            "convictingCourtCode": "2577",
            "wording": "Has a violent past and fear that he will commit further offences and interfere with witnesse",
            "startDate": "2020-09-18",
            "results": [
              {
                "resultIdentifier": "969f150c-cd05-46b0-9dd9-30891efcc766",
                "publishedForNows": false,
                "prompts": [
                  {
                    "promptIdentifier": "7cd1472f-2379-4f5b-9e67-98a43d86e122",
                    "promptReference": "AOF",
                    "label": "Amount of fine",
                    "value": "Â£100.00"
                  }
                ],
                "resultDefinitionGroup": "Imposition",
                "d20": false,
                "label": "Fine"
              }
            ]
          }
        ]
      }
    ]
  },
  "isReshare": true,
  "orderingHearingId": "0f97e46a-8e4a-49c4-8849-53f8157972be"
}
