=== hmcts/cpp-context-staging-dvla/stagingdvla-domain/stagingdvla-domain-message/src/raml/json/schema/stagingdvla.event.driver-search-audit-report-requested.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/cpp/stagingdvla/event/driver-search-audit-report-requested.json",
  "description": "Driver record search audit report request, capturing report search criteria, date, creator etc",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "userId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "dateTime": {
      "type": "string",
      "format": "date"
    },
    "reportSearchCriteria": {
      "$ref": "http://justice.gov.uk/cpp/stagingdvla/driver-audit-report-search-criteria.json"
    }
  },
  "required": [
    "id",
    "userId",
    "dateTime",
    "reportSearchCriteria"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-event/stagingdvla-event-processor/src/yaml/json/stagingdvla.event.driver-search-audit-report-requested.json
{
  "id": "a7e6d378-8cf1-11eb-8dcd-0242ac130003",
  "userId": "b3454b32-8cf1-11eb-8dcd-0242ac130003",
  "dateTime":"2024-01-01T21:34:09.387Z",
  "reportSearchCriteria": {
    "email": "eltonjohn12345@co.uk",
    "driverNumber": "DRIVER1002101212121",
    "startDate": "2024-01-01",
    "endDate": "2024-01-02"
  }
}
